version: "3.3"

networks:
  traefik_traefik:
    external: true
  outside-pi-overlay:
    external: true
  prestashop:
    internal: true

services:
  web:
    build:
      context: .
      dockerfile: ./bin/docker/images/prestashop/Dockerfile
    image: ${REGISTRY_URL}/${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
    networks:
      - traefik_traefik
      - prestashop
      - outside-pi-overlay
    env_file:
      - ./bin/docker/conf/acceptance/env
    deploy:
      labels:
        - "traefik.frontend.rule=Host:${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.hipay-pos-platform.com"
        - "traefik.port=80"
        - "traefik.docker.network=traefik_traefik"
  database:
    image: mysql:5.7
    env_file:
      - ./bin/docker/conf/acceptance/env
    networks:
      prestashop:
        aliases:
          - ${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}_database
  smtp:
    image: hipay/mailcatcher:1.0.0
    networks:
      traefik_traefik:
      prestashop:
        aliases:
          - ${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}_smtp
    deploy:
      labels:
        - "traefik.frontend.rule=Host:${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-mail.hipay-pos-platform.com"
        - "traefik.port=1080"
        - "traefik.docker.network=traefik_traefik"
